name: Build

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build Translate
      run: |
        git config --global url."https://github.com/".insteadOf git://github.com/
        cd translate
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
          ./gen_rc.sh
        fi
      shell: bash
      continue-on-error: true
    - run: nuget restore AudioPlaybackConnector.sln
    - name: Build Solution
      run: |
        msbuild AudioPlaybackConnector.sln "-p:Configuration=Release;Platform=x64"
        msbuild AudioPlaybackConnector.sln "-p:Configuration=Release;Platform=x86"
      shell: powershell
    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.exe
    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector32
        path: Release/AudioPlaybackConnector32.exe



